import './Teleprompter.css';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Activity, CheckCircle2, FlipHorizontal, Gauge, Mic, Pause, Play, RotateCcw, X } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { buildSessionMetrics, compareSessions, countScriptUnits, createScriptKey, getScrollCompletion } from '../domain/sessionMetrics';
import { useAppStore } from '../store';
import type { Language, PracticeSession, PrompterMode, SessionComparison, SessionStatus } from '../types';

interface TeleprompterProps { title: string; script: string; targetPace: number; lang: Language; prompterMode: PrompterMode; onClose: () => void; }
type VoiceState = 'SPEAKING' | 'SILENCE' | 'UNAVAILABLE';
const LONG_PAUSE_MS = 1500; const SPEECH_GRACE_MS = 650;
const createId = () => crypto.randomUUID?.() || `${Date.now()}_${Math.random().toString(36).slice(2)}`;
const formatDuration = (milliseconds: number) => { const seconds = Math.max(0, Math.round(milliseconds / 1000)); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`; };
function comparisonSentence(comparison: SessionComparison | null, lang: Language): string {
  if (!comparison) return lang === 'zh' ? '这是该稿件的第一次可比较练习。' : 'This is the first comparable rehearsal for this script.';
  const improvements: string[] = [];
  if (comparison.durationDeltaMs < -1000) improvements.push(lang === 'zh' ? `用时缩短 ${Math.round(Math.abs(comparison.durationDeltaMs) / 1000)} 秒` : `${Math.round(Math.abs(comparison.durationDeltaMs) / 1000)}s faster`);
  if (comparison.longPauseDelta < 0) improvements.push(lang === 'zh' ? `长停顿减少 ${Math.abs(comparison.longPauseDelta)} 次` : `${Math.abs(comparison.longPauseDelta)} fewer long pauses`);
  if (comparison.completionDelta > 0.03) improvements.push(lang === 'zh' ? `完成度提高 ${Math.round(comparison.completionDelta * 100)}%` : `${Math.round(comparison.completionDelta * 100)}% higher completion`);
  if (improvements.length > 0) return improvements.join(lang === 'zh' ? '，' : ', ');
  return lang === 'zh' ? '本次与上次整体接近，可继续关注长停顿和完成度。' : 'This attempt is close to the previous one; focus on long pauses and completion.';
}

export function Teleprompter({ title, script, targetPace, lang, prompterMode, onClose }: TeleprompterProps) {
  const addRecording = useAppStore((state) => state.addRecording); const addSession = useAppStore((state) => state.addSession); const sessions = useAppStore((state) => state.sessions); const audioProfile = useAppStore((state) => state.audioProfile);
  const [status, setStatus] = useState<SessionStatus>('idle'); const [voiceState, setVoiceState] = useState<VoiceState>('UNAVAILABLE'); const [isMirrored, setIsMirrored] = useState(false); const [audioLevel, setAudioLevel] = useState(0); const [elapsedMs, setElapsedMs] = useState(0); const [liveEstimatedPace, setLiveEstimatedPace] = useState(0); const [pixelsPerSecond, setPixelsPerSecond] = useState(0); const [audioMessage, setAudioMessage] = useState(''); const [completedSession, setCompletedSession] = useState<PracticeSession | null>(null); const [comparison, setComparison] = useState<SessionComparison | null>(null);
  const statusRef = useRef<SessionStatus>('idle'); const scrollRef = useRef<HTMLDivElement>(null); const streamRef = useRef<MediaStream | null>(null); const audioContextRef = useRef<AudioContext | null>(null); const recorderRef = useRef<MediaRecorder | null>(null); const chunksRef = useRef<Blob[]>([]); const audioRafRef = useRef(0); const clockRafRef = useRef(0); const scrollRafRef = useRef(0); const totalTimeRef = useRef(0); const speakingTimeRef = useRef(0); const longPauseCountRef = useRef(0); const silenceStartRef = useRef(0); const longPauseCountedRef = useRef(false); const hasSpokenRef = useRef(false); const noiseFloorRef = useRef(0.008); const startedAtRef = useRef(0); const currentSessionIdRef = useRef(''); const savedRef = useRef(false); const manualScrollUntilRef = useRef(0); const previousVoiceRef = useRef<VoiceState>('UNAVAILABLE');
  const totalUnits = useMemo(() => countScriptUnits(script, lang), [lang, script]); const scriptKey = useMemo(() => createScriptKey(title, script, lang), [lang, script, title]); const isRunning = status === 'running'; const isPaused = status === 'paused'; const canResume = isPaused || status === 'ready';
  const updateStatus = useCallback((next: SessionStatus) => { statusRef.current = next; setStatus(next); }, []);
  const cleanupAudio = useCallback(() => { if (audioRafRef.current) cancelAnimationFrame(audioRafRef.current); audioRafRef.current = 0; if (recorderRef.current && recorderRef.current.state !== 'inactive') { try { recorderRef.current.stop(); } catch { /* stopping */ } } recorderRef.current = null; streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; if (audioContextRef.current && audioContextRef.current.state !== 'closed') void audioContextRef.current.close(); audioContextRef.current = null; }, []);
  useEffect(() => () => { if (clockRafRef.current) cancelAnimationFrame(clockRafRef.current); if (scrollRafRef.current) cancelAnimationFrame(scrollRafRef.current); cleanupAudio(); }, [cleanupAudio]);

  const prepareAudio = useCallback(async (): Promise<boolean> => {
    if (audioContextRef.current && streamRef.current) return true;
    if (!navigator.mediaDevices?.getUserMedia) { setVoiceState('UNAVAILABLE'); setAudioMessage(lang === 'zh' ? '当前浏览器不支持麦克风分析。' : 'Microphone analysis is not supported in this browser.'); return false; }
    updateStatus('requesting_permission');
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true, autoGainControl: audioProfile === 'raw', channelCount: 1 } }); streamRef.current = stream;
      const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioContextClass) throw new Error('AudioContext unavailable');
      const context = new AudioContextClass(); audioContextRef.current = context; const source = context.createMediaStreamSource(stream); const recordingDestination = context.createMediaStreamDestination(); const analyser = context.createAnalyser(); analyser.fftSize = 256;
      let output: AudioNode = source;
      if (audioProfile !== 'raw') { const highpass = context.createBiquadFilter(); highpass.type = 'highpass'; highpass.frequency.value = audioProfile === 'broadcast' ? 90 : 75; const presence = context.createBiquadFilter(); presence.type = 'peaking'; presence.frequency.value = audioProfile === 'broadcast' ? 3900 : 2800; presence.Q.value = 0.9; presence.gain.value = audioProfile === 'broadcast' ? 2.5 : 1.3; const compressor = context.createDynamicsCompressor(); compressor.threshold.value = audioProfile === 'broadcast' ? -25 : -20; compressor.ratio.value = audioProfile === 'broadcast' ? 4 : 2.5; compressor.attack.value = 0.008; compressor.release.value = 0.18; source.connect(highpass); highpass.connect(presence); presence.connect(compressor); output = compressor; }
      if (audioProfile === 'raw') { source.connect(analyser); source.connect(recordingDestination); } else { const limiter = context.createDynamicsCompressor(); limiter.threshold.value = -2; limiter.knee.value = 0; limiter.ratio.value = 12; limiter.attack.value = 0.002; limiter.release.value = 0.08; output.connect(limiter); limiter.connect(analyser); limiter.connect(recordingDestination); }
      const mimeCandidates = ['audio/webm;codecs=opus', 'audio/webm', 'audio/mp4']; const mimeType = mimeCandidates.find((candidate) => typeof MediaRecorder !== 'undefined' && MediaRecorder.isTypeSupported(candidate));
      if (typeof MediaRecorder !== 'undefined') { const recorder = new MediaRecorder(recordingDestination.stream, mimeType ? { mimeType } : undefined); recorderRef.current = recorder; recorder.ondataavailable = (event) => { if (event.data.size > 0) chunksRef.current.push(event.data); }; recorder.onstop = () => { if (chunksRef.current.length === 0) return; const blob = new Blob(chunksRef.current, { type: recorder.mimeType || mimeType || 'audio/webm' }); addRecording({ id: createId(), sessionId: currentSessionIdRef.current || undefined, url: URL.createObjectURL(blob), name: `${title || 'RhythmCoach'}_${new Date().toLocaleTimeString().replace(/:/g, '-')}`, durationSec: Math.round(totalTimeRef.current / 1000), blob, mimeType: blob.type, createdAt: Date.now() }); chunksRef.current = []; }; }
      const data = new Uint8Array(analyser.fftSize); let lastFrame = performance.now(); let lastUiUpdate = 0;
      const analyse = (time: number) => { const delta = Math.min(250, Math.max(0, time - lastFrame)); lastFrame = time; analyser.getByteTimeDomainData(data); let sum = 0; for (let index = 0; index < data.length; index += 1) { const amplitude = (data[index] - 128) / 128; sum += amplitude * amplitude; } const rms = Math.sqrt(sum / data.length); const threshold = Math.max(0.015, noiseFloorRef.current * 2.6); let speakingNow = rms > threshold;
        if (!speakingNow) { noiseFloorRef.current = noiseFloorRef.current * 0.97 + rms * 0.03; if (silenceStartRef.current === 0) silenceStartRef.current = time; const silenceDuration = time - silenceStartRef.current; speakingNow = silenceDuration < SPEECH_GRACE_MS; if (hasSpokenRef.current && silenceDuration >= LONG_PAUSE_MS && !longPauseCountedRef.current && statusRef.current === 'running') { longPauseCountRef.current += 1; longPauseCountedRef.current = true; } } else { hasSpokenRef.current = true; silenceStartRef.current = 0; longPauseCountedRef.current = false; }
        const nextVoice: VoiceState = speakingNow ? 'SPEAKING' : 'SILENCE'; if (nextVoice !== previousVoiceRef.current) { previousVoiceRef.current = nextVoice; setVoiceState(nextVoice); } if (statusRef.current === 'running' && speakingNow) speakingTimeRef.current += delta; if (time - lastUiUpdate > 80) { setAudioLevel(Math.min(1, rms * 16)); lastUiUpdate = time; } audioRafRef.current = requestAnimationFrame(analyse); };
      audioRafRef.current = requestAnimationFrame(analyse); setAudioMessage(''); setVoiceState('SILENCE'); updateStatus('ready'); return true;
    } catch (error) { console.error('Microphone setup failed:', error); setVoiceState('UNAVAILABLE'); setAudioMessage(lang === 'zh' ? '无法使用麦克风。定时和自由模式仍可继续，但语音跟随不可用。' : 'Microphone unavailable. Timed and free modes can continue; voice-follow mode cannot.'); updateStatus('error'); return false; }
  }, [addRecording, audioProfile, lang, title, updateStatus]);

  useEffect(() => { let lastFrame = performance.now(); let lastUi = 0; const tick = (time: number) => { const delta = Math.min(250, Math.max(0, time - lastFrame)); lastFrame = time; if (statusRef.current === 'running') totalTimeRef.current += delta; if (time - lastUi > 250) { setElapsedMs(totalTimeRef.current); const progress = getScrollCompletion(scrollRef.current); const completedUnits = Math.round(totalUnits * progress); const speakingMinutes = speakingTimeRef.current / 60_000; setLiveEstimatedPace(speakingMinutes > 0.03 ? Math.round(completedUnits / speakingMinutes) : 0); lastUi = time; } clockRafRef.current = requestAnimationFrame(tick); }; clockRafRef.current = requestAnimationFrame(tick); return () => cancelAnimationFrame(clockRafRef.current); }, [totalUnits]);
  useEffect(() => { const updateScrollSpeed = () => { const element = scrollRef.current; if (!element || prompterMode === 'free' || targetPace <= 0 || totalUnits === 0) { setPixelsPerSecond(0); return; } const maxScroll = Math.max(0, element.scrollHeight - element.clientHeight); const targetSeconds = (totalUnits / targetPace) * 60; setPixelsPerSecond(targetSeconds > 0 ? maxScroll / targetSeconds : 0); }; updateScrollSpeed(); const timeout = window.setTimeout(updateScrollSpeed, 120); window.addEventListener('resize', updateScrollSpeed); return () => { window.clearTimeout(timeout); window.removeEventListener('resize', updateScrollSpeed); }; }, [prompterMode, script, targetPace, totalUnits]);
  useEffect(() => { let lastFrame = performance.now(); const scroll = (time: number) => { const delta = Math.min(100, Math.max(0, time - lastFrame)); lastFrame = time; const shouldAutoScroll = statusRef.current === 'running' && prompterMode !== 'free' && time >= manualScrollUntilRef.current && pixelsPerSecond > 0 && (prompterMode === 'timed' || voiceState === 'SPEAKING'); if (shouldAutoScroll && scrollRef.current) scrollRef.current.scrollTop += (pixelsPerSecond * delta) / 1000; scrollRafRef.current = requestAnimationFrame(scroll); }; scrollRafRef.current = requestAnimationFrame(scroll); return () => cancelAnimationFrame(scrollRafRef.current); }, [pixelsPerSecond, prompterMode, voiceState]);

  const startOrResume = useCallback(async () => { if (statusRef.current === 'running' || statusRef.current === 'finishing' || statusRef.current === 'completed') return; if (!startedAtRef.current) { startedAtRef.current = Date.now(); currentSessionIdRef.current = createId(); savedRef.current = false; } let audioReady = Boolean(audioContextRef.current); if (!audioReady) audioReady = await prepareAudio(); if (!audioReady && prompterMode === 'follow') { updateStatus('error'); return; } silenceStartRef.current = 0; longPauseCountedRef.current = false; const recorder = recorderRef.current; if (recorder) { if (recorder.state === 'inactive') { chunksRef.current = []; recorder.start(1000); } else if (recorder.state === 'paused') recorder.resume(); } updateStatus('running'); }, [prepareAudio, prompterMode, updateStatus]);
  const pauseSession = useCallback(() => { if (statusRef.current !== 'running') return; if (recorderRef.current?.state === 'recording') recorderRef.current.pause(); silenceStartRef.current = 0; longPauseCountedRef.current = false; updateStatus('paused'); }, [updateStatus]);
  const finishSession = useCallback(() => { if (savedRef.current || statusRef.current === 'finishing' || statusRef.current === 'completed') return; if (!startedAtRef.current || totalTimeRef.current < 500) { setAudioMessage(lang === 'zh' ? '请先开始训练，再生成复盘。' : 'Start the rehearsal before creating a summary.'); if (statusRef.current !== 'error') updateStatus('idle'); return; } updateStatus('finishing'); const endedAt = Date.now(); const completionRatio = getScrollCompletion(scrollRef.current); const metrics = buildSessionMetrics({ totalTimeMs: totalTimeRef.current, speakingTimeMs: speakingTimeRef.current, longPauseCount: longPauseCountRef.current, completionRatio, totalUnits, targetPace: prompterMode === 'free' ? null : targetPace, lang }); const session: PracticeSession = { id: currentSessionIdRef.current || createId(), scriptKey, scriptTitle: title, scriptSnapshot: script, lang, mode: prompterMode, startedAt: startedAtRef.current || endedAt, endedAt, metrics }; const previous = sessions.find((item) => item.scriptKey === scriptKey); setComparison(previous ? compareSessions(session, previous) : null); addSession(session); savedRef.current = true; setCompletedSession(session); if (recorderRef.current && recorderRef.current.state !== 'inactive') recorderRef.current.stop(); updateStatus('completed'); }, [addSession, lang, prompterMode, script, scriptKey, sessions, targetPace, title, totalUnits, updateStatus]);
  const close = useCallback(() => { if (statusRef.current === 'completed' || totalTimeRef.current < 1000) { cleanupAudio(); onClose(); return; } finishSession(); }, [cleanupAudio, finishSession, onClose]);
  useEffect(() => { const handleKey = (event: KeyboardEvent) => { if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement) return; if (event.code === 'Space') { event.preventDefault(); if (statusRef.current === 'running') pauseSession(); else void startOrResume(); } else if (event.code === 'Escape') { event.preventDefault(); finishSession(); } else if (event.code === 'ArrowDown' || event.code === 'ArrowUp') { event.preventDefault(); manualScrollUntilRef.current = performance.now() + 1500; if (scrollRef.current) scrollRef.current.scrollTop += event.code === 'ArrowDown' ? 70 : -70; } }; window.addEventListener('keydown', handleKey); return () => window.removeEventListener('keydown', handleKey); }, [finishSession, pauseSession, startOrResume]);
  const manualScroll = () => { manualScrollUntilRef.current = performance.now() + 1500; };
  const modeLabel = lang === 'zh' ? prompterMode === 'timed' ? '定时提词' : prompterMode === 'follow' ? '语音跟随' : '自由演讲' : prompterMode === 'timed' ? 'Timed' : prompterMode === 'follow' ? 'Voice Follow' : 'Free';
  const paceValue = prompterMode === 'free' ? liveEstimatedPace : targetPace; const paceLabel = prompterMode === 'free' ? (lang === 'zh' ? '进度估算' : 'Progress estimate') : (lang === 'zh' ? '目标语速' : 'Target pace');
  const statusLabel = lang === 'zh' ? ({ idle: '待开始', requesting_permission: '请求权限', ready: '已就绪', running: '训练中', paused: '已暂停', finishing: '生成复盘', completed: '已完成', error: '麦克风不可用' } as Record<SessionStatus, string>)[status] : status.replaceAll('_', ' ');

  return <motion.div className="prompter-shell" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
    <header className="prompter-topbar"><div className="session-state"><span className={`status-dot ${isRunning ? 'running' : ''}`} /><div><strong>{modeLabel}</strong><span>{formatDuration(elapsedMs)} · {statusLabel}</span></div></div><div className="top-actions"><button className="btn-icon" onClick={() => setIsMirrored((value) => !value)} title="Mirror"><FlipHorizontal size={20} /></button><button className="btn-icon finish-button" onClick={finishSession} title="Finish"><CheckCircle2 size={21} /></button><button className="btn-icon close-button" onClick={close} title="Close"><X size={21} /></button></div></header>
    <motion.aside drag dragMomentum={false} className="pace-panel"><div className="pace-panel-row"><span className={`voice-label ${voiceState.toLowerCase()}`}><Activity size={17} />{voiceState === 'SPEAKING' ? (lang === 'zh' ? '正在讲话' : 'Speaking') : voiceState === 'SILENCE' ? (lang === 'zh' ? '停顿' : 'Silence') : (lang === 'zh' ? '无麦克风数据' : 'No microphone data')}</span><button className="btn-icon" onClick={() => isRunning ? pauseSession() : void startOrResume()}>{isRunning ? <Pause size={19} fill="currentColor" /> : <Play size={19} fill="currentColor" />}</button></div><div className="pace-number"><strong>{paceValue || '—'}</strong><span>{lang === 'zh' ? 'CPM' : 'WPM'}</span></div><div className="pace-caption"><Gauge size={15} /> {paceLabel}</div><p>{prompterMode === 'timed' ? (lang === 'zh' ? '按目标时长连续滚动；停顿不会暂停。' : 'Continuous scrolling to the target duration.') : prompterMode === 'follow' ? (lang === 'zh' ? '检测到讲话时滚动；长停顿后暂停。' : 'Scrolls while speaking and pauses during silence.') : (lang === 'zh' ? '手动滚动；语速仅按文本进度估算。' : 'Manual scrolling; pace is estimated from text progress.')}</p><div className="audio-meter" aria-label="audio level">{Array.from({ length: 14 }).map((_, index) => <span key={index} className={audioLevel * 14 > index ? 'active' : ''} />)}</div>{audioMessage && <div className="audio-warning"><Mic size={15} /> {audioMessage}</div>}</motion.aside>
    <div className="prompter-frame">{!isRunning && !completedSession && <button className="central-play" onClick={() => canResume || status === 'idle' || status === 'error' ? void startOrResume() : undefined}>{isPaused ? <RotateCcw size={38} /> : <Play size={42} fill="currentColor" />}<span>{isPaused ? (lang === 'zh' ? '继续训练' : 'Resume') : (lang === 'zh' ? '开始训练' : 'Start')}</span></button>}<div ref={scrollRef} className={`prompter-scroll ${isMirrored ? 'mirrored' : ''}`} onWheel={manualScroll} onTouchMove={manualScroll} onScroll={prompterMode === 'free' ? manualScroll : undefined}><div className="prompter-padding"><div className="prompter-text">{script.split('\n').filter((line) => line.trim()).map((line, index) => <p key={`${index}_${line.slice(0, 12)}`}>{line}</p>)}</div></div></div></div>
    <AnimatePresence>{completedSession && <motion.div className="summary-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.section className="summary-modal glass-panel" initial={{ scale: .94, y: 16 }} animate={{ scale: 1, y: 0 }}><h2>{lang === 'zh' ? '本次训练完成' : 'Rehearsal complete'}</h2><p className="summary-note">{lang === 'zh' ? '估算语速基于文本滚动进度与有效发声时长，不等同于逐字语音识别结果。' : 'Estimated pace uses text progress and speaking time; it is not word-level speech recognition.'}</p><div className="summary-grid"><div><span>{lang === 'zh' ? '实际用时' : 'Total time'}</span><strong>{formatDuration(completedSession.metrics.totalTimeMs)}</strong></div><div><span>{lang === 'zh' ? '有效发声' : 'Speaking time'}</span><strong>{formatDuration(completedSession.metrics.speakingTimeMs)}</strong></div><div><span>{lang === 'zh' ? '完成度' : 'Completion'}</span><strong>{Math.round(completedSession.metrics.completionRatio * 100)}%</strong></div><div><span>{lang === 'zh' ? '长停顿' : 'Long pauses'}</span><strong>{completedSession.metrics.longPauseCount}</strong></div><div><span>{lang === 'zh' ? '估算语速' : 'Estimated pace'}</span><strong>{completedSession.metrics.estimatedPace || '—'} {completedSession.metrics.paceUnit}</strong></div><div><span>{lang === 'zh' ? '发声占比' : 'Speaking ratio'}</span><strong>{Math.round(completedSession.metrics.speakingRatio * 100)}%</strong></div></div><div className="comparison-callout"><strong>{lang === 'zh' ? '与上次相比' : 'Compared with previous'}</strong><span>{comparisonSentence(comparison, lang)}</span></div><button className="btn" onClick={() => { cleanupAudio(); onClose(); }} style={{ width: '100%', justifyContent: 'center' }}>{lang === 'zh' ? '返回并查看训练记录' : 'Return to history'}</button></motion.section></motion.div>}</AnimatePresence>
  </motion.div>;
}
